# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('quota', models.IntegerField()),
                ('disabled', models.BooleanField()),
                ('redirectTarget', models.CharField(blank=True, max_length=200)),
                ('catchAll', models.BooleanField()),
                ('enableAutoReply', models.BooleanField()),
                ('autoReplyText', models.TextField(blank=True)),
                ('domain', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailadmin.Domain'))
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailadmin.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Mailinglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accounts', models.ManyToManyField(to='mailadmin.Account')),
                ('domain', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailadmin.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailadmin.Domain')),
            ],
        ),
    ]
