# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-26 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailadmin', '0003_auto_20161120_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
