# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0006_auto_20161126_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='redirects',
            field=models.ManyToManyField(to='mailadmin.Redirect'),
        ),
    ]
