# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0007_mailinglist_redirects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='domain',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailadmin.Domain'),
        ),
    ]
