# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0008_auto_20161127_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=200)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailadmin.Mailinglist')),
            ],
        ),
    ]
