# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0010_auto_20161204_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalreceiver',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailadmin.Mailinglist'),
        ),
    ]
