# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models

def migrate_disabled_to_active(apps, schema_editor):
    Domain = apps.get_model('mailadmin', 'Domain')
    for domain in Domain.objects.all():
        domain.active = not domain.disabled
        domain.save()
    Account = apps.get_model('mailadmin', 'Account')
    for account in Account.objects.all():
        account.active = not account.disabled
        account.save()

def migrate_active_to_disabled(apps, schema_editor):
    Domain = apps.get_model('mailadmin', 'Domain')
    for domain in Domain.objects.all:
        domain.disabled = not domain.active
        domain.save()
    Account = apps.get_model('mailadmin', 'Account')
    for account in Account.objects.all():
        account.disabled = not account.active
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0011_auto_20161204_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(migrate_disabled_to_active, migrate_active_to_disabled),
        migrations.RemoveField(
            model_name='domain',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='account',
            name='disabled',
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
