# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0014_auto_20170108_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditions',
            name='roles',
            field=models.CharField(choices=[('0', 'User'), ('1', 'Privileged'), ('2', 'Domain admin'), ('4', 'Admin')], default=None, max_length=10),
        ),
    ]
