# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0015_auto_20170108_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mailinglists',
            field=models.ManyToManyField(to='mailadmin.Mailinglist'),
        ),
        migrations.AddField(
            model_name='domain',
            name='administrators',
            field=models.ManyToManyField(to='mailadmin.UserAdditions'),
        ),
        migrations.AlterField(
            model_name='useradditions',
            name='roles',
            field=models.CharField(choices=[('0', 'User'), ('1', 'Privileged'), ('2', 'Domain admin'), ('4', 'Admin')], default=0, max_length=10),
        ),
    ]
