# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0016_auto_20170108_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='administrators',
        ),
        migrations.AddField(
            model_name='useradditions',
            name='domains',
            field=models.ManyToManyField(to='mailadmin.Domain'),
        ),
    ]
