# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0017_auto_20170108_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='mailinglists',
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='accounts',
            field=models.ManyToManyField(related_name='mailinglists', to='mailadmin.Account'),
        ),
        migrations.AlterField(
            model_name='useradditions',
            name='domains',
            field=models.ManyToManyField(related_name='administrators', to='mailadmin.Domain'),
        ),
    ]
