# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0018_auto_20170108_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditions',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='administrators', to='mailadmin.Domain'),
        ),
    ]
