# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailadmin', '0019_auto_20170108_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='domain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mailinglists', to='mailadmin.Domain'),
        ),
    ]
